version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cfe_db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ConsentFormEngine.WebAPI/Dockerfile
    container_name: cfe_api
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ConsentFormEngineDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True

volumes:
  mssql_data:
